### ISSUE TITLE
Use HTTP HEAD request for --num-pages instead of GET

### ISSUE THREAD

**Issue by jordilin** [jordilin/gitar#160]
We only care about the LINK headers in order to retrieve the number of pages available for the given resource.

**Comment by BipulLamsal** [comment]
hey could you guide me on this i want to work on this issue

**Comment by jordilin** [comment]
yes, basically when a user requests number of pages available in a resource with the `--num-pages` cli flag in list operations, the code does a GET HTTP request in https://github.com/jordilin/gitar/blob/main/src/remote/query.rs#L48 That is not really necessary as we only care about the link headers in the response. So, technically a HEAD is only needed. For that to happen, we need to add support for a HEAD request in the http module, client struct - https://github.com/jordilin/gitar/blob/main/src/http.rs#L333 Implementation should be close to how the GET is implemented except that the server does not send a response body back. A test would also be required to verify functionality on the dependency being used `ureq`. That can be done in here https://github.com/jordilin/gitar/blob/main/tests/http_test.rs#L26 - You can take the `test_http_runner` as a reference which does a GET request. The server mock being used can be set to return a link header like for example 

```
link: <https://api.github.com/repositories/683565078/pulls?state=closed&page=2>; rel="next", <https://api.github.com/repositories/683565078/pulls?state=closed&page=5>; rel="last"
```
and an empty body.
Make sure to run `cargo test` and `cargo fmt` so all tests pass and code is automatically formatted. Thanks!!
